### PR TITLE
🐛🤖 Fix burnt ticket date/time display and i18n on /order/id/tickets

### LINKED ISSUE #2451: 🐛 "This ticket has been scanned le {date} à {time} and is not valid anymore" on burned event ticket
Image

But on global view / print all :

Image

### PR DESCRIPTION
**Pull request by Tirodem**
Remove {date} and {time} from burnt tickets and put good values instead, and remove "le" "à" (french translation artifacts) from EN and NL languages.

Fixes #2451

### CODE REVIEW

**Comment by Tirodem** [comment]
image
QA OK ✅

File: src/routes/(app)/order/[id]/tickets/+page.svelte [hunk 1]
```diff
@@ -46,7 +46,12 @@
 			<img src="/ticket/{ticket.ticketId}/qrcode" alt="QR code" class="h-96 w-96" />
 
 			{#if ticket.scanned}
-				<p>{t('ticket.scanned')}</p>
+				<p>
+					{t('ticket.scanned', {
+						date: new Date(ticket.scanned.at).toLocaleDateString(),
+						time: new Date(ticket.scanned.at).toLocaleTimeString()
+					})}
+				</p>
```
Comment (gntw) [inline src/routes/(app)/order/[id]/tickets/+page.svelte:55]: {@const scannedDate = new Date(ticket.scanned.at)}
  <p>
      {t('ticket.scanned', {
          date: scannedDate.toLocaleDateString(),
          time: scannedDate.toLocaleTimeString()
      })}
  </p>

Comment (gntw) [reply src/routes/(app)/order/[id]/tickets/+page.svelte:55]: Thank you, also please rebase the branch from main

Comment (Tirodem) [reply src/routes/(app)/order/[id]/tickets/+page.svelte:55]: Done
