### PR TITLE
🦋 Fix PWYW product prices to display with VAT when enabled

### LINKED ISSUE #2240: 🦋 If be-BOP display price VAT included PWYW Products price value entered by customer should also be VAT included
Currently when a customer choose a price for a PWYW items on a VAT included be-BOP it doesn't include VAT. It should.

### PR DESCRIPTION
**Pull request by gntw**
- PWYW products now display minimum, recommended, and maximum prices **with VAT included** when the setting is enabled - matching the behavior of regular products.

Closes #2240

### CODE REVIEW

**Comment by Tirodem** [comment]
If I have to resume the issue, is : when "Display VAT included estimated price in product page" is enable, when I fill the price of a PWYW product, the stocked price should be the filled value minus product VAT

It's about the price chosen by customer, not the minimum / recommended / maximum price chosen by the shop's owner

So, if I set a price of 5€ of a 20% VAT product as a customer :
- if "Display VAT included estimated price in product page" is disabled :
  - VAT excluded price = 5€
  - VAT excluded price = 6€
- if "Display VAT included estimated price in product page" is enabled :
  - VAT excluded price = 4,1667€
  - VAT excluded price = 5€

**Comment by gntw** [comment]
@Tirodem its done ! ready for QA

**Comment by Tirodem** [comment]
Works like a charm 👌 
@roosemberth for review

File: src/routes/(app)/product/[id]/+page.svelte [hunk 1]
```diff
@@ -85,21 +89,40 @@
...
-	const PWYWMinimum = toCurrency(
-		PWYWCurrency,
-		data.product.price.amount,
-		data.product.price.currency
-	);
+	const PWYWMinimum = computePriceForDisplay(
+		toCurrency(PWYWCurrency, data.product.price.amount, data.product.price.currency) *
+			vatMultiplier(rate, data.displayVatIncludedInProduct),
+		PWYWCurrency
+	).amount;
```
Comment (roosemberth) [inline src/routes/(app)/product/[id]/+page.svelte]: Why are we binding the amount value instead of keeping the price?
I'm not a fan of keeping amount values without currency (or units) around. It makes computation bugs easy to miss.

The same remark applies to other parts of code.

File: src/lib/utils/vat.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+	return vatProfile?.rates[country] ?? vatRate(country);
+}
+
+/**
+ * Returns VAT multiplier: 1.0 if VAT should not be applied, or (1 + rate/100) if it should
+ */
+export function vatMultiplier(rate: number, shouldApplyVat: boolean): number {
+	return shouldApplyVat ? 1 + rate / 100 : 1;
+}
```
Comment (roosemberth) [inline src/lib/utils/vat.ts:40]: The `vat` is always defined, regardless of whether we should apply it in a calculation.

I find problematic to have a function with an argument that effectively disables the function. I think it should be the responsibility of the caller to know whether to apply vat or (like it already is, through the argument) and call the correct function accordingly.

If we want to make this code lighter, we can change the semantic of this to something like “price with or without vat to display” and move the logic checking the runtime config here.

The same comment applies to other functions with an argument to bypass the function in this file.

File: src/routes/(app)/product/[id]/+page.svelte [hunk 3]
```diff
@@ -85,21 +89,40 @@
 		});
 	let deposit = 'partial';
 
+	const rate = computeVatRate({
```
Comment (roosemberth) [inline src/routes/(app)/product/[id]/+page.svelte]: `vatRate`.

**Review by roosemberth — CHANGES_REQUESTED** [review]

**Comment by roosemberth** [comment]
@gntw changes look good, thanks!

I'm piggybacking this PR to check automatic generation of artifacts links with https://www.artifact.ci/.

Branch has not been re-QA'd by @Tirodem, but changes look simple enough, so I'm merging anyways. I'll pay him a couple beers if this breaks main.
